/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gui.logindanregist;  
  
import connect.connect_database;
import java.awt.Color;  
import javax.swing.JOptionPane;  
import java.security.MessageDigest;  
import java.security.NoSuchAlgorithmException;  
import java.sql.Connection;  
import java.sql.PreparedStatement;  
import java.sql.ResultSet;  
import java.sql.SQLException;  
  
/**  
 *  
 * @author ASUS  
 */  
public class login extends javax.swing.JFrame {  
  
    public static String nama;  
    public static String email;  
    public static String username;
    public static String password;
  
    public login() {  
        initComponents();  
        Color bg = new Color(128, 128, 128);  
        getContentPane().setBackground(bg);  
    }  
  
    // Metode untuk melakukan hashing password  
    private String hashPassword(String password) {  
        try {  
            MessageDigest md = MessageDigest.getInstance("SHA-256");  
            byte[] hash = md.digest(password.getBytes());  
            StringBuilder sb = new StringBuilder();  
            for (byte b : hash) {  
                sb.append(String.format("%02x", b));  
            }  
            return sb.toString();  
        } catch (NoSuchAlgorithmException e) {  
            e.printStackTrace();  
            return null;  
        }  
    }  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsernameLogin = new javax.swing.JTextField();
        btnLog = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnReg = new javax.swing.JButton();
        txtPasswordLogin = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel3.setText("LOGIN");

        txtUsernameLogin.setBackground(new java.awt.Color(204, 0, 0));
        txtUsernameLogin.setForeground(new java.awt.Color(255, 255, 255));
        txtUsernameLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameLoginActionPerformed(evt);
            }
        });

        btnLog.setBackground(new java.awt.Color(102, 0, 0));
        btnLog.setForeground(new java.awt.Color(255, 255, 255));
        btnLog.setText("Login");
        btnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogActionPerformed(evt);
            }
        });

        jLabel4.setText("Belum punya akun?");

        btnReg.setBackground(new java.awt.Color(102, 0, 0));
        btnReg.setForeground(new java.awt.Color(255, 255, 255));
        btnReg.setText("Register");
        btnReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegActionPerformed(evt);
            }
        });

        txtPasswordLogin.setBackground(new java.awt.Color(204, 0, 0));
        txtPasswordLogin.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("silahkan login terlebih dahulu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(74, 74, 74))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(btnLog))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(txtUsernameLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPasswordLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsernameLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPasswordLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(btnLog)
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReg)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogActionPerformed
        // TODO add your handling code here:
        //        if ((txtUsernameLog.getText().equals(Register.username))
//                && (txtPassLog.getText().equals(Register.pass))) {
//            
//            dispose();
//            
//            Welcome wel = new Welcome();
//            wel.setVisible(true);
//
//            wel.pack();
//            wel.setLocationRelativeTo(null);
//            wel.setDefaultCloseOperation(Login.EXIT_ON_CLOSE);
//        } else {
//            JOptionPane.showMessageDialog(this, "Akun tidak ditemukan, pastikan anda memiliki akun dan cek kembali", "Warnning", JOptionPane.WARNING_MESSAGE);
//        }

        // Koneksi ke database
       Connection conn = connect_database.getConnection();  
  
if (txtUsernameLogin.getText().trim().isEmpty() || txtPasswordLogin.getPassword().length == 0) {  
    JOptionPane.showMessageDialog(this, "Username dan Password harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);  
    return;  
}  
  
PreparedStatement stmt = null;  
ResultSet rs = null;  
  
try {  
    // Query SQL untuk memeriksa data  
    String sql = "SELECT nama, email, username, password FROM users WHERE username = ?";  
    stmt = conn.prepareStatement(sql);  
    stmt.setString(1, txtUsernameLogin.getText().trim());  
  
    rs = stmt.executeQuery();  
  
    if (rs.next()) {  
        // Ambil password yang di-hash dari database  
        String hashedPassword = rs.getString("password");  
  
        // Cocokkan password  
        if (hashedPassword.equals(hashPassword(new String(txtPasswordLogin.getPassword())))) {  
            nama = rs.getString("nama"); // Simpan nama, email dan username pengguna  
            email = rs.getString("email");  
            username = rs.getString("username");
            password = rs.getString("password");
  
            // Menutup frame saat ini dan membuka frame menu  
            dispose();  
            menu home = new menu();  
            home.setVisible(true);  
            home.pack();  
            home.setLocationRelativeTo(null);  
            home.setDefaultCloseOperation(login.EXIT_ON_CLOSE);  
        } else {  
            JOptionPane.showMessageDialog(this, "Password salah!", "Error", JOptionPane.ERROR_MESSAGE);  
        }  
    } else {  
        JOptionPane.showMessageDialog(this, "Akun tidak ditemukan, pastikan sudah register!", "Warning", JOptionPane.WARNING_MESSAGE);  
    }  
} catch (SQLException e) {  
    e.printStackTrace();  
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);  
} finally {  
    // Menutup ResultSet dan PreparedStatement  
    try {  
        if (rs != null) {  
            rs.close();  
        }  
        if (stmt != null) {  
            stmt.close();  
        }  
        if (conn != null) {  
            conn.close(); // Menutup koneksi  
        }  
    } catch (SQLException e) {  
        e.printStackTrace();  
    }  
}     
    }//GEN-LAST:event_btnLogActionPerformed

    private void btnRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegActionPerformed
        // TODO add your handling code here:
        dispose();

        register reg = new register();
        reg.setVisible(true);

        reg.pack();
        reg.setLocationRelativeTo(null);
        reg.setDefaultCloseOperation(register.EXIT_ON_CLOSE);
    }//GEN-LAST:event_btnRegActionPerformed

    private void txtUsernameLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLog;
    private javax.swing.JButton btnReg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField txtPasswordLogin;
    private javax.swing.JTextField txtUsernameLogin;
    // End of variables declaration//GEN-END:variables
}
