/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gui.logindanregist;

import javax.swing.JOptionPane;
import connect.connect_database;
import java.awt.Color;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
/**
 *
 * @author ASUS
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    public static String nama;
    public static String username;
    public static String password;
    public static String email;
     
    public register() {
        initComponents();
         Color bg = new Color(128, 128, 128);
           getContentPane().setBackground(bg);
    }
    
    
//    hashpassword
    private String hashPassword(String password) {
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            byte[] hash = md.digest(password.getBytes());
            StringBuilder sb = new StringBuilder();
            for (byte b : hash) {
                sb.append(String.format("%02x", b));
            }
            return sb.toString();
        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
            return null;
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsernameRegister = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnregisReg = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        btnloginReg = new javax.swing.JButton();
        txtPasswordRegister = new javax.swing.JPasswordField();
        txtRePasswordRegister = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        txtNamaRegister = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEmailRegister = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtUsernameRegister.setBackground(new java.awt.Color(204, 0, 0));
        txtUsernameRegister.setForeground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Humanst521 BT", 0, 12)); // NOI18N
        jLabel9.setText("Username");

        jLabel1.setFont(new java.awt.Font("Humnst777 Cn BT", 0, 14)); // NOI18N
        jLabel1.setText("silahkan regist untuk menggunakan fitur aplikasi");

        jLabel10.setFont(new java.awt.Font("Humanst521 BT", 0, 12)); // NOI18N
        jLabel10.setText("Password");

        jLabel11.setFont(new java.awt.Font("Humanst521 BT", 0, 12)); // NOI18N
        jLabel11.setText("Re-password");

        jLabel3.setText("-");

        btnregisReg.setBackground(new java.awt.Color(102, 0, 0));
        btnregisReg.setForeground(new java.awt.Color(255, 255, 255));
        btnregisReg.setText("register");
        btnregisReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregisRegActionPerformed(evt);
            }
        });

        jLabel12.setText("Sudah punya akun?");

        btnloginReg.setBackground(new java.awt.Color(102, 0, 0));
        btnloginReg.setForeground(new java.awt.Color(255, 255, 255));
        btnloginReg.setText("Login");
        btnloginReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginRegActionPerformed(evt);
            }
        });

        txtPasswordRegister.setBackground(new java.awt.Color(204, 0, 0));
        txtPasswordRegister.setForeground(new java.awt.Color(255, 255, 255));

        txtRePasswordRegister.setBackground(new java.awt.Color(204, 0, 0));
        txtRePasswordRegister.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel6.setText("REGISTER");

        txtNamaRegister.setBackground(new java.awt.Color(204, 0, 0));
        txtNamaRegister.setForeground(new java.awt.Color(255, 255, 255));
        txtNamaRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaRegisterActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Humanst521 BT", 0, 12)); // NOI18N
        jLabel7.setText("Nama");

        txtEmailRegister.setBackground(new java.awt.Color(204, 0, 0));
        txtEmailRegister.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Humanst521 BT", 0, 12)); // NOI18N
        jLabel8.setText("Email");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(28, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNamaRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                        .addComponent(jLabel7)
                                        .addComponent(txtEmailRegister))
                                    .addComponent(jLabel9)
                                    .addComponent(txtUsernameRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel10)
                                            .addComponent(txtPasswordRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                            .addComponent(jLabel11)
                                            .addComponent(txtRePasswordRegister)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnloginReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnregisReg)
                                        .addGap(23, 23, 23))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(57, 57, 57)
                                .addComponent(jLabel3)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNamaRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPasswordRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmailRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(txtRePasswordRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUsernameRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnregisReg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnloginReg)
                                .addGap(17, 17, 17))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnregisRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregisRegActionPerformed
        // TODO add your handling code here:
        Connection conn = connect_database.getConnection();  
  
if (txtPasswordRegister.getText().equals(new String(txtRePasswordRegister.getPassword()))) {  
    // Validasi input  
    if (txtNamaRegister.getText().trim().isEmpty() ||   
        txtEmailRegister.getText().trim().isEmpty() ||  
        txtPasswordRegister.getText().trim().isEmpty() ||   
        txtRePasswordRegister.getPassword().length == 0) {  
          
        JOptionPane.showMessageDialog(this, "Semua kolom harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);  
        return;  
    }  
  
    // Hash password menggunakan SHA-256 atau bcrypt (opsional)  
    String hashedPassword = hashPassword(new String(txtPasswordRegister.getPassword()));  
  
    PreparedStatement stmt = null;  
    try {  
        
        String sql = "INSERT INTO users (nama, email, username, password) VALUES (?, ?, ?, ?)";  
        stmt = conn.prepareStatement(sql);  
        stmt.setString(1, txtNamaRegister.getText().trim());  
        stmt.setString(2, txtEmailRegister.getText().trim());  
        stmt.setString(3, txtUsernameRegister.getText().trim());  
        stmt.setString(4, hashedPassword);  
  
        
        stmt.executeUpdate();  
        JOptionPane.showMessageDialog(this, "Akun berhasil dibuat, silahkan login!", "Informasi", JOptionPane.INFORMATION_MESSAGE);  
  
        
        dispose();  
  
      
        login Lg = new login();  
        Lg.setVisible(true);  
        Lg.pack();  
        Lg.setLocationRelativeTo(null);  
        Lg.setDefaultCloseOperation(register.EXIT_ON_CLOSE);
  
    } catch (SQLException e) {  
        e.printStackTrace();  
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);  
    } finally {  
        // Menutup statement dan koneksi  
        try {  
            if (stmt != null) {  
                stmt.close();  
            }  
            if (conn != null) {  
                conn.close();  
            }  
        } catch (SQLException e) {  
            e.printStackTrace(); 
            JOptionPane.showMessageDialog(this, "error: " + e.getMessage(), "error", JOptionPane.ERROR_MESSAGE);
        }  
    }  
} else {  
    JOptionPane.showMessageDialog(this, "Password yang diinput berbeda, silahkan input ulang Password dengan benar", "Konfirmasi", JOptionPane.ERROR_MESSAGE);  
}  

    }//GEN-LAST:event_btnregisRegActionPerformed

    private void btnloginRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginRegActionPerformed
        // TODO add your handling code here:
        dispose();

        login Log = new login();
        Log.setVisible(true);

        Log.pack();
        Log.setLocationRelativeTo(null);
        Log.setDefaultCloseOperation(login.EXIT_ON_CLOSE);
    }//GEN-LAST:event_btnloginRegActionPerformed

    private void txtNamaRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnloginReg;
    private javax.swing.JButton btnregisReg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtEmailRegister;
    private javax.swing.JTextField txtNamaRegister;
    private javax.swing.JPasswordField txtPasswordRegister;
    private javax.swing.JPasswordField txtRePasswordRegister;
    private javax.swing.JTextField txtUsernameRegister;
    // End of variables declaration//GEN-END:variables
}
